# Generated by Django 3.0.5 on 2020-04-29 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200425_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='compositiontemp',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='productinshop',
            name='availability',
            field=models.BooleanField(default=True),
        ),
    ]
