# Generated by Django 3.0.5 on 2020-04-20 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200420_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composition',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='composition', to='products.Product', unique=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='en_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='ingredientsgroup',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='originalsection',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='original_section', to='products.Product', unique=True),
        ),
    ]
