# Generated by Django 3.0.5 on 2020-04-30 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200429_1106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='composition',
            old_name='composition',
            new_name='ingredients',
        ),
        migrations.RenameField(
            model_name='compositiontemp',
            old_name='composition',
            new_name='ingredients',
        ),
    ]
