# Generated by Django 3.0.5 on 2020-05-01 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200430_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compositiontemp',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='section',
        ),
        migrations.RemoveField(
            model_name='productinshop',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productinshop',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='sectiontemp',
            name='product',
        ),
        migrations.DeleteModel(
            name='Composition',
        ),
        migrations.DeleteModel(
            name='CompositionTemp',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductInShop',
        ),
        migrations.DeleteModel(
            name='SectionTemp',
        ),
    ]
