# Generated by Django 3.0.5 on 2020-04-21 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200420_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='group',
        ),
        migrations.RemoveField(
            model_name='originalsection',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='section',
        ),
        migrations.RemoveField(
            model_name='section',
            name='parent',
        ),
        migrations.DeleteModel(
            name='Composition',
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
        migrations.DeleteModel(
            name='IngredientsGroup',
        ),
        migrations.DeleteModel(
            name='OriginalSection',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
