# Generated by Django 3.0.5 on 2020-05-19 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_composition_compositiontemp_product_productinshop_sectiontemp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='last_updated',
        ),
        migrations.AddField(
            model_name='productinshop',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='productinshop',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_in_shops', to='products.Product'),
        ),
        migrations.AlterField(
            model_name='productinshop',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='available_products', to='products.Shop'),
        ),
        migrations.AlterField(
            model_name='section',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='products.Section'),
        ),
        migrations.AlterField(
            model_name='section',
            name='slug',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
