# Generated by Django 3.0.7 on 2020-09-29 08:45

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0009_auto_20200521_1650'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientsgroup',
            old_name='name',
            new_name='groupname',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='function',
        ),
        migrations.AlterField(
            model_name='composition',
            name='ingredients',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=[]), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='compositiontemp',
            name='ingredients',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(default=[]), blank=True, null=True, size=None),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favourite_products', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=set()), blank=True, null=True, size=None)),
                ('exclude_ingrs', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=set()), blank=True, null=True, size=None)),
                ('include_ingrs', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=set()), blank=True, null=True, size=None)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
