# Generated by Django 3.0.7 on 2020-10-05 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20201005_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectiontemp',
            name='section',
            field=models.TextField(blank=True, null=True),
        ),
    ]
