# Generated by Django 3.1.2 on 2020-12-05 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20201205_1613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientsgroup',
            old_name='groupname',
            new_name='name',
        ),
    ]
